# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Easyrpc < Formula
  desc "EasyRPC is an easy-to-use gRPC client."
  homepage "https://github.com/heartandu/easyrpc/"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heartandu/easyrpc/releases/download/v0.3.0/easyrpc_0.3.0_darwin_x86_64.tar.gz"
      sha256 "9d2111ecc303153057ea76c2e1be6e60a0d36df4e1284fd8c4b9618c0d7a29a5"

      def install
        bin.install "easyrpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heartandu/easyrpc/releases/download/v0.3.0/easyrpc_0.3.0_darwin_arm64.tar.gz"
      sha256 "4d41d232b0c5e92cfa9c8d82d2c8c857d12577d3f55993e1bd6427db04465b18"

      def install
        bin.install "easyrpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartandu/easyrpc/releases/download/v0.3.0/easyrpc_0.3.0_linux_x86_64.tar.gz"
      sha256 "2d3967751a883c76946c939a665c7463c05ad0c07b2e162bc081aa9fd2a17ee0"
      def install
        bin.install "easyrpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartandu/easyrpc/releases/download/v0.3.0/easyrpc_0.3.0_linux_arm64.tar.gz"
      sha256 "79ca49efc2f3730945d8dea75c8a00e22bc48525da0c879eef9e96c35ae23b8b"
      def install
        bin.install "easyrpc"
      end
    end
  end
end
