# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Easyrpc < Formula
  desc "EasyRPC is an easy-to-use gRPC client."
  homepage "https://github.com/heartandu/easyrpc/"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heartandu/easyrpc/releases/download/v0.2.1/easyrpc_0.2.1_darwin_x86_64.tar.gz"
      sha256 "a3b70c58244fa6fcd0412951cea17499ea7f1b183e94c6fca50fb047e12935bd"

      def install
        bin.install "easyrpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heartandu/easyrpc/releases/download/v0.2.1/easyrpc_0.2.1_darwin_arm64.tar.gz"
      sha256 "5da93c2374d7cbc074723893012a900c650dd272ad2d62712b27b72bc32f0d5e"

      def install
        bin.install "easyrpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartandu/easyrpc/releases/download/v0.2.1/easyrpc_0.2.1_linux_x86_64.tar.gz"
      sha256 "60d3e20f1fd2207ffe97979094c9169627e0acf4169781016cdbe9aabc19cca4"
      def install
        bin.install "easyrpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartandu/easyrpc/releases/download/v0.2.1/easyrpc_0.2.1_linux_arm64.tar.gz"
      sha256 "3cbafedc85917a8282e3eb6d0358d04c1f6dfb3830c7c0d6cb37642b618fe743"
      def install
        bin.install "easyrpc"
      end
    end
  end
end
