# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Easyrpc < Formula
  desc "EasyRPC is an easy-to-use gRPC client."
  homepage "https://github.com/heartandu/easyrpc/"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/heartandu/easyrpc/releases/download/v0.1.1/easyrpc_0.1.1_darwin_x86_64.tar.gz"
      sha256 "0066836e1771cb4f6d38c2f51c2f79b56ed6cd6a3e76c64428fd81208c501209"

      def install
        bin.install "easyrpc"
      end
    end
    on_arm do
      url "https://github.com/heartandu/easyrpc/releases/download/v0.1.1/easyrpc_0.1.1_darwin_arm64.tar.gz"
      sha256 "0a4b3226557e5418f79bf634972719b65dc7abc2df01e924409b4fe65e757599"

      def install
        bin.install "easyrpc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/heartandu/easyrpc/releases/download/v0.1.1/easyrpc_0.1.1_linux_x86_64.tar.gz"
        sha256 "9b92c6487e95c7956dcf7f4d612a35a8c5b0c43d66fd4634f39706d49dddbb7c"

        def install
          bin.install "easyrpc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/heartandu/easyrpc/releases/download/v0.1.1/easyrpc_0.1.1_linux_arm64.tar.gz"
        sha256 "839af439fbd5152ecf008945dbb7a45a643f87b3075c42abfc24ccea3d19cacf"

        def install
          bin.install "easyrpc"
        end
      end
    end
  end
end
