# This file was generated by GoReleaser. DO NOT EDIT.
cask "easyrpc" do
  name "easyrpc"
  desc "EasyRPC is an easy-to-use gRPC client.
Inspired by grpcurl and evans and aims to ease the process of querying protobuf RPCs from a terminal.
"
  homepage "https://github.com/heartandu/easyrpc/"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "easyrpc"

  on_macos do
    on_intel do
      url "https://github.com/heartandu/easyrpc/releases/download/v#{version}/easyrpc_#{version}_darwin_x86_64.tar.gz"
      sha256 "2d61cfc3131dba2305df198a2e12d4b76c9cf23d3d33a7df7f7f912cc21093e8"
    end
    on_arm do
      url "https://github.com/heartandu/easyrpc/releases/download/v#{version}/easyrpc_#{version}_darwin_arm64.tar.gz"
      sha256 "fe1ddde5780579e424d14d1f62aeb7040ab83b23a968587e66e829022dd7e293"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/heartandu/easyrpc/releases/download/v#{version}/easyrpc_#{version}_linux_x86_64.tar.gz"
      sha256 "b145a596fbd4ff89505307b8079b5af36982b6e39362ae93d29017127a14abc8"
    end
    on_arm do
      url "https://github.com/heartandu/easyrpc/releases/download/v#{version}/easyrpc_#{version}_linux_arm64.tar.gz"
      sha256 "6d1710136072d46f7a9433d505101fc8a22b70097173cd2f7e3b2755789c57b5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/easyrpc"]
    end
  end

  # No zap stanza required
end
