# This file was generated by GoReleaser. DO NOT EDIT.
cask "easyrpc" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "cf87cda8543fcec9f7ec7c2b2843f01541f38d4fdd4fb6fef78a950783ccfaca"
      url "https://github.com/heartandu/easyrpc/releases/download/v#{version}/easyrpc_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4b1dc57d7e2cb4dd51ce2162bfcb82d30484bccb9d3af513f3903dbd62e52581"
      url "https://github.com/heartandu/easyrpc/releases/download/v#{version}/easyrpc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8306098ebfa7aeb7ab19aa2c77c1ef486000d8e1d8638243f4b08420008ebe6f"
      url "https://github.com/heartandu/easyrpc/releases/download/v#{version}/easyrpc_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3a1f5734b6a199842d76567cbf5f1410488cc6428582f73470cc80f5082b9210"
      url "https://github.com/heartandu/easyrpc/releases/download/v#{version}/easyrpc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "easyrpc"
  desc "EasyRPC is an easy-to-use gRPC client.
Inspired by grpcurl and evans and aims to ease the process of querying protobuf RPCs from a terminal.
"
  homepage "https://github.com/heartandu/easyrpc/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "easyrpc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/easyrpc"]
    end
  end

  # No zap stanza required

end
