# This file was generated by GoReleaser. DO NOT EDIT.
cask "easyrpc" do
  name "easyrpc"
  desc "EasyRPC is an easy-to-use gRPC client.
Inspired by grpcurl and evans and aims to ease the process of querying protobuf RPCs from a terminal.
"
  homepage "https://github.com/heartandu/easyrpc/"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "easyrpc"

  on_macos do
    on_intel do
      url "https://github.com/heartandu/easyrpc/releases/download/v#{version}/easyrpc_#{version}_darwin_x86_64.tar.gz"
      sha256 "b9fd848f94ae371eb9ea88f1ebb729d9d313ef5c40f1bc8d71e17a5bc943ae84"
    end
    on_arm do
      url "https://github.com/heartandu/easyrpc/releases/download/v#{version}/easyrpc_#{version}_darwin_arm64.tar.gz"
      sha256 "96f8a8881f77977954b625dd65d7c22a7bd608d5f05cd58bb1dc594d54c75a06"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/heartandu/easyrpc/releases/download/v#{version}/easyrpc_#{version}_linux_x86_64.tar.gz"
      sha256 "0f0bb24e052f0491fca280545bb7c732013d9ba84843d63c8a73c0a24926bfd3"
    end
    on_arm do
      url "https://github.com/heartandu/easyrpc/releases/download/v#{version}/easyrpc_#{version}_linux_arm64.tar.gz"
      sha256 "d14fe23ab6e3e4b9fe74daf33f3ee42eb09b994651075e2ae993f8af007f4ff4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/easyrpc"]
    end
  end

  # No zap stanza required
end
